services:
  fastapi_app:
    build: .
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - ./jwt_app:/jwt_app
      - ./tests:/tests
      - ./pytest.ini:/pytest.ini
    ports:
      - 8000:8000
    command: >
      sh -c "alembic upgrade head && python3 main.py"

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1201
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s