"""empty message

Revision ID: d24df1b5f456
Revises: 0f25e4adc241
Create Date: 2025-01-17 09:46:51.622297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24df1b5f456'
down_revision: Union[str, None] = '0f25e4adc241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'readers', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readers', type_='unique')
    # ### end Alembic commands ###
